/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubmitPostFormdataRouteImport } from './routes/submit-post-formdata'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SerializeFormDataRouteImport } from './routes/serialize-form-data'
import { Route as ReturnNullRouteImport } from './routes/return-null'
import { Route as RawResponseRouteImport } from './routes/raw-response'
import { Route as ProgressiveEnhancementTestRouteImport } from './routes/progressive-enhancement-test'
import { Route as ProgressiveEnhancementSerializationTestRouteImport } from './routes/progressive-enhancement-serialization-test'
import { Route as ProgressiveEnhancementRedirectTestRouteImport } from './routes/progressive-enhancement-redirect-test'
import { Route as ProgressiveEnhancementMultipleRouteImport } from './routes/progressive-enhancement-multiple'
import { Route as MultipartRouteImport } from './routes/multipart'
import { Route as IsomorphicFnsRouteImport } from './routes/isomorphic-fns'
import { Route as HeadersRouteImport } from './routes/headers'
import { Route as EnvOnlyRouteImport } from './routes/env-only'
import { Route as DeadCodePreserveRouteImport } from './routes/dead-code-preserve'
import { Route as ConsistentRouteImport } from './routes/consistent'
import { Route as AbortSignalRouteImport } from './routes/abort-signal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormdataRedirectIndexRouteImport } from './routes/formdata-redirect/index'
import { Route as CookiesIndexRouteImport } from './routes/cookies/index'
import { Route as RedirectTargetNameRouteImport } from './routes/redirect-target/$name'
import { Route as CookiesSetRouteImport } from './routes/cookies/set'
import { Route as FormdataRedirectTargetNameRouteImport } from './routes/formdata-redirect/target.$name'

const SubmitPostFormdataRoute = SubmitPostFormdataRouteImport.update({
  id: '/submit-post-formdata',
  path: '/submit-post-formdata',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SerializeFormDataRoute = SerializeFormDataRouteImport.update({
  id: '/serialize-form-data',
  path: '/serialize-form-data',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnNullRoute = ReturnNullRouteImport.update({
  id: '/return-null',
  path: '/return-null',
  getParentRoute: () => rootRouteImport,
} as any)
const RawResponseRoute = RawResponseRouteImport.update({
  id: '/raw-response',
  path: '/raw-response',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressiveEnhancementTestRoute =
  ProgressiveEnhancementTestRouteImport.update({
    id: '/progressive-enhancement-test',
    path: '/progressive-enhancement-test',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgressiveEnhancementSerializationTestRoute =
  ProgressiveEnhancementSerializationTestRouteImport.update({
    id: '/progressive-enhancement-serialization-test',
    path: '/progressive-enhancement-serialization-test',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgressiveEnhancementRedirectTestRoute =
  ProgressiveEnhancementRedirectTestRouteImport.update({
    id: '/progressive-enhancement-redirect-test',
    path: '/progressive-enhancement-redirect-test',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProgressiveEnhancementMultipleRoute =
  ProgressiveEnhancementMultipleRouteImport.update({
    id: '/progressive-enhancement-multiple',
    path: '/progressive-enhancement-multiple',
    getParentRoute: () => rootRouteImport,
  } as any)
const MultipartRoute = MultipartRouteImport.update({
  id: '/multipart',
  path: '/multipart',
  getParentRoute: () => rootRouteImport,
} as any)
const IsomorphicFnsRoute = IsomorphicFnsRouteImport.update({
  id: '/isomorphic-fns',
  path: '/isomorphic-fns',
  getParentRoute: () => rootRouteImport,
} as any)
const HeadersRoute = HeadersRouteImport.update({
  id: '/headers',
  path: '/headers',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvOnlyRoute = EnvOnlyRouteImport.update({
  id: '/env-only',
  path: '/env-only',
  getParentRoute: () => rootRouteImport,
} as any)
const DeadCodePreserveRoute = DeadCodePreserveRouteImport.update({
  id: '/dead-code-preserve',
  path: '/dead-code-preserve',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsistentRoute = ConsistentRouteImport.update({
  id: '/consistent',
  path: '/consistent',
  getParentRoute: () => rootRouteImport,
} as any)
const AbortSignalRoute = AbortSignalRouteImport.update({
  id: '/abort-signal',
  path: '/abort-signal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormdataRedirectIndexRoute = FormdataRedirectIndexRouteImport.update({
  id: '/formdata-redirect/',
  path: '/formdata-redirect/',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesIndexRoute = CookiesIndexRouteImport.update({
  id: '/cookies/',
  path: '/cookies/',
  getParentRoute: () => rootRouteImport,
} as any)
const RedirectTargetNameRoute = RedirectTargetNameRouteImport.update({
  id: '/redirect-target/$name',
  path: '/redirect-target/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesSetRoute = CookiesSetRouteImport.update({
  id: '/cookies/set',
  path: '/cookies/set',
  getParentRoute: () => rootRouteImport,
} as any)
const FormdataRedirectTargetNameRoute =
  FormdataRedirectTargetNameRouteImport.update({
    id: '/formdata-redirect/target/$name',
    path: '/formdata-redirect/target/$name',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/abort-signal': typeof AbortSignalRoute
  '/consistent': typeof ConsistentRoute
  '/dead-code-preserve': typeof DeadCodePreserveRoute
  '/env-only': typeof EnvOnlyRoute
  '/headers': typeof HeadersRoute
  '/isomorphic-fns': typeof IsomorphicFnsRoute
  '/multipart': typeof MultipartRoute
  '/progressive-enhancement-multiple': typeof ProgressiveEnhancementMultipleRoute
  '/progressive-enhancement-redirect-test': typeof ProgressiveEnhancementRedirectTestRoute
  '/progressive-enhancement-serialization-test': typeof ProgressiveEnhancementSerializationTestRoute
  '/progressive-enhancement-test': typeof ProgressiveEnhancementTestRoute
  '/raw-response': typeof RawResponseRoute
  '/return-null': typeof ReturnNullRoute
  '/serialize-form-data': typeof SerializeFormDataRoute
  '/status': typeof StatusRoute
  '/submit-post-formdata': typeof SubmitPostFormdataRoute
  '/cookies/set': typeof CookiesSetRoute
  '/redirect-target/$name': typeof RedirectTargetNameRoute
  '/cookies': typeof CookiesIndexRoute
  '/formdata-redirect': typeof FormdataRedirectIndexRoute
  '/formdata-redirect/target/$name': typeof FormdataRedirectTargetNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/abort-signal': typeof AbortSignalRoute
  '/consistent': typeof ConsistentRoute
  '/dead-code-preserve': typeof DeadCodePreserveRoute
  '/env-only': typeof EnvOnlyRoute
  '/headers': typeof HeadersRoute
  '/isomorphic-fns': typeof IsomorphicFnsRoute
  '/multipart': typeof MultipartRoute
  '/progressive-enhancement-multiple': typeof ProgressiveEnhancementMultipleRoute
  '/progressive-enhancement-redirect-test': typeof ProgressiveEnhancementRedirectTestRoute
  '/progressive-enhancement-serialization-test': typeof ProgressiveEnhancementSerializationTestRoute
  '/progressive-enhancement-test': typeof ProgressiveEnhancementTestRoute
  '/raw-response': typeof RawResponseRoute
  '/return-null': typeof ReturnNullRoute
  '/serialize-form-data': typeof SerializeFormDataRoute
  '/status': typeof StatusRoute
  '/submit-post-formdata': typeof SubmitPostFormdataRoute
  '/cookies/set': typeof CookiesSetRoute
  '/redirect-target/$name': typeof RedirectTargetNameRoute
  '/cookies': typeof CookiesIndexRoute
  '/formdata-redirect': typeof FormdataRedirectIndexRoute
  '/formdata-redirect/target/$name': typeof FormdataRedirectTargetNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/abort-signal': typeof AbortSignalRoute
  '/consistent': typeof ConsistentRoute
  '/dead-code-preserve': typeof DeadCodePreserveRoute
  '/env-only': typeof EnvOnlyRoute
  '/headers': typeof HeadersRoute
  '/isomorphic-fns': typeof IsomorphicFnsRoute
  '/multipart': typeof MultipartRoute
  '/progressive-enhancement-multiple': typeof ProgressiveEnhancementMultipleRoute
  '/progressive-enhancement-redirect-test': typeof ProgressiveEnhancementRedirectTestRoute
  '/progressive-enhancement-serialization-test': typeof ProgressiveEnhancementSerializationTestRoute
  '/progressive-enhancement-test': typeof ProgressiveEnhancementTestRoute
  '/raw-response': typeof RawResponseRoute
  '/return-null': typeof ReturnNullRoute
  '/serialize-form-data': typeof SerializeFormDataRoute
  '/status': typeof StatusRoute
  '/submit-post-formdata': typeof SubmitPostFormdataRoute
  '/cookies/set': typeof CookiesSetRoute
  '/redirect-target/$name': typeof RedirectTargetNameRoute
  '/cookies/': typeof CookiesIndexRoute
  '/formdata-redirect/': typeof FormdataRedirectIndexRoute
  '/formdata-redirect/target/$name': typeof FormdataRedirectTargetNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/abort-signal'
    | '/consistent'
    | '/dead-code-preserve'
    | '/env-only'
    | '/headers'
    | '/isomorphic-fns'
    | '/multipart'
    | '/progressive-enhancement-multiple'
    | '/progressive-enhancement-redirect-test'
    | '/progressive-enhancement-serialization-test'
    | '/progressive-enhancement-test'
    | '/raw-response'
    | '/return-null'
    | '/serialize-form-data'
    | '/status'
    | '/submit-post-formdata'
    | '/cookies/set'
    | '/redirect-target/$name'
    | '/cookies'
    | '/formdata-redirect'
    | '/formdata-redirect/target/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/abort-signal'
    | '/consistent'
    | '/dead-code-preserve'
    | '/env-only'
    | '/headers'
    | '/isomorphic-fns'
    | '/multipart'
    | '/progressive-enhancement-multiple'
    | '/progressive-enhancement-redirect-test'
    | '/progressive-enhancement-serialization-test'
    | '/progressive-enhancement-test'
    | '/raw-response'
    | '/return-null'
    | '/serialize-form-data'
    | '/status'
    | '/submit-post-formdata'
    | '/cookies/set'
    | '/redirect-target/$name'
    | '/cookies'
    | '/formdata-redirect'
    | '/formdata-redirect/target/$name'
  id:
    | '__root__'
    | '/'
    | '/abort-signal'
    | '/consistent'
    | '/dead-code-preserve'
    | '/env-only'
    | '/headers'
    | '/isomorphic-fns'
    | '/multipart'
    | '/progressive-enhancement-multiple'
    | '/progressive-enhancement-redirect-test'
    | '/progressive-enhancement-serialization-test'
    | '/progressive-enhancement-test'
    | '/raw-response'
    | '/return-null'
    | '/serialize-form-data'
    | '/status'
    | '/submit-post-formdata'
    | '/cookies/set'
    | '/redirect-target/$name'
    | '/cookies/'
    | '/formdata-redirect/'
    | '/formdata-redirect/target/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbortSignalRoute: typeof AbortSignalRoute
  ConsistentRoute: typeof ConsistentRoute
  DeadCodePreserveRoute: typeof DeadCodePreserveRoute
  EnvOnlyRoute: typeof EnvOnlyRoute
  HeadersRoute: typeof HeadersRoute
  IsomorphicFnsRoute: typeof IsomorphicFnsRoute
  MultipartRoute: typeof MultipartRoute
  ProgressiveEnhancementMultipleRoute: typeof ProgressiveEnhancementMultipleRoute
  ProgressiveEnhancementRedirectTestRoute: typeof ProgressiveEnhancementRedirectTestRoute
  ProgressiveEnhancementSerializationTestRoute: typeof ProgressiveEnhancementSerializationTestRoute
  ProgressiveEnhancementTestRoute: typeof ProgressiveEnhancementTestRoute
  RawResponseRoute: typeof RawResponseRoute
  ReturnNullRoute: typeof ReturnNullRoute
  SerializeFormDataRoute: typeof SerializeFormDataRoute
  StatusRoute: typeof StatusRoute
  SubmitPostFormdataRoute: typeof SubmitPostFormdataRoute
  CookiesSetRoute: typeof CookiesSetRoute
  RedirectTargetNameRoute: typeof RedirectTargetNameRoute
  CookiesIndexRoute: typeof CookiesIndexRoute
  FormdataRedirectIndexRoute: typeof FormdataRedirectIndexRoute
  FormdataRedirectTargetNameRoute: typeof FormdataRedirectTargetNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/submit-post-formdata': {
      id: '/submit-post-formdata'
      path: '/submit-post-formdata'
      fullPath: '/submit-post-formdata'
      preLoaderRoute: typeof SubmitPostFormdataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/serialize-form-data': {
      id: '/serialize-form-data'
      path: '/serialize-form-data'
      fullPath: '/serialize-form-data'
      preLoaderRoute: typeof SerializeFormDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return-null': {
      id: '/return-null'
      path: '/return-null'
      fullPath: '/return-null'
      preLoaderRoute: typeof ReturnNullRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raw-response': {
      id: '/raw-response'
      path: '/raw-response'
      fullPath: '/raw-response'
      preLoaderRoute: typeof RawResponseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progressive-enhancement-test': {
      id: '/progressive-enhancement-test'
      path: '/progressive-enhancement-test'
      fullPath: '/progressive-enhancement-test'
      preLoaderRoute: typeof ProgressiveEnhancementTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progressive-enhancement-serialization-test': {
      id: '/progressive-enhancement-serialization-test'
      path: '/progressive-enhancement-serialization-test'
      fullPath: '/progressive-enhancement-serialization-test'
      preLoaderRoute: typeof ProgressiveEnhancementSerializationTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progressive-enhancement-redirect-test': {
      id: '/progressive-enhancement-redirect-test'
      path: '/progressive-enhancement-redirect-test'
      fullPath: '/progressive-enhancement-redirect-test'
      preLoaderRoute: typeof ProgressiveEnhancementRedirectTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progressive-enhancement-multiple': {
      id: '/progressive-enhancement-multiple'
      path: '/progressive-enhancement-multiple'
      fullPath: '/progressive-enhancement-multiple'
      preLoaderRoute: typeof ProgressiveEnhancementMultipleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multipart': {
      id: '/multipart'
      path: '/multipart'
      fullPath: '/multipart'
      preLoaderRoute: typeof MultipartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/isomorphic-fns': {
      id: '/isomorphic-fns'
      path: '/isomorphic-fns'
      fullPath: '/isomorphic-fns'
      preLoaderRoute: typeof IsomorphicFnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/headers': {
      id: '/headers'
      path: '/headers'
      fullPath: '/headers'
      preLoaderRoute: typeof HeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/env-only': {
      id: '/env-only'
      path: '/env-only'
      fullPath: '/env-only'
      preLoaderRoute: typeof EnvOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dead-code-preserve': {
      id: '/dead-code-preserve'
      path: '/dead-code-preserve'
      fullPath: '/dead-code-preserve'
      preLoaderRoute: typeof DeadCodePreserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consistent': {
      id: '/consistent'
      path: '/consistent'
      fullPath: '/consistent'
      preLoaderRoute: typeof ConsistentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/abort-signal': {
      id: '/abort-signal'
      path: '/abort-signal'
      fullPath: '/abort-signal'
      preLoaderRoute: typeof AbortSignalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formdata-redirect/': {
      id: '/formdata-redirect/'
      path: '/formdata-redirect'
      fullPath: '/formdata-redirect'
      preLoaderRoute: typeof FormdataRedirectIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies/': {
      id: '/cookies/'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redirect-target/$name': {
      id: '/redirect-target/$name'
      path: '/redirect-target/$name'
      fullPath: '/redirect-target/$name'
      preLoaderRoute: typeof RedirectTargetNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies/set': {
      id: '/cookies/set'
      path: '/cookies/set'
      fullPath: '/cookies/set'
      preLoaderRoute: typeof CookiesSetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formdata-redirect/target/$name': {
      id: '/formdata-redirect/target/$name'
      path: '/formdata-redirect/target/$name'
      fullPath: '/formdata-redirect/target/$name'
      preLoaderRoute: typeof FormdataRedirectTargetNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbortSignalRoute: AbortSignalRoute,
  ConsistentRoute: ConsistentRoute,
  DeadCodePreserveRoute: DeadCodePreserveRoute,
  EnvOnlyRoute: EnvOnlyRoute,
  HeadersRoute: HeadersRoute,
  IsomorphicFnsRoute: IsomorphicFnsRoute,
  MultipartRoute: MultipartRoute,
  ProgressiveEnhancementMultipleRoute: ProgressiveEnhancementMultipleRoute,
  ProgressiveEnhancementRedirectTestRoute:
    ProgressiveEnhancementRedirectTestRoute,
  ProgressiveEnhancementSerializationTestRoute:
    ProgressiveEnhancementSerializationTestRoute,
  ProgressiveEnhancementTestRoute: ProgressiveEnhancementTestRoute,
  RawResponseRoute: RawResponseRoute,
  ReturnNullRoute: ReturnNullRoute,
  SerializeFormDataRoute: SerializeFormDataRoute,
  StatusRoute: StatusRoute,
  SubmitPostFormdataRoute: SubmitPostFormdataRoute,
  CookiesSetRoute: CookiesSetRoute,
  RedirectTargetNameRoute: RedirectTargetNameRoute,
  CookiesIndexRoute: CookiesIndexRoute,
  FormdataRedirectIndexRoute: FormdataRedirectIndexRoute,
  FormdataRedirectTargetNameRoute: FormdataRedirectTargetNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
